package com.mediconnect.service;

import com.mediconnect.config.Database;
import com.mediconnect.model.*;
import com.mediconnect.util.PasswordUtil;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.*;

/** MySQL-backed workflow implementation using prepared statements and JDBC transactions. */
public final class JdbcPlatformService implements MediConnectService {
    private static final String USER_COLUMNS = "id,name,email,password_hash,role,active";
    public JdbcPlatformService() {
        try (Connection c = Database.connect(); Statement s = c.createStatement()) {
            s.executeQuery("SELECT 1 FROM users LIMIT 1").close();
            bootstrapAdminIfConfigured(c);
        } catch (SQLException ex) { throw new IllegalStateException("MySQL mode could not connect or find the schema. Check credentials and run database/schema.sql. " + ex.getMessage(), ex); }
    }
    private void bootstrapAdminIfConfigured(Connection c) throws SQLException {
        String email = System.getenv("MEDICONNECT_INITIAL_ADMIN_EMAIL");
        if (email == null || email.isBlank()) return;
        String name = System.getenv("MEDICONNECT_INITIAL_ADMIN_NAME"), password = System.getenv("MEDICONNECT_INITIAL_ADMIN_PASSWORD");
        if (name == null || password == null || password.length() < 12) throw new IllegalStateException("Set MEDICONNECT_INITIAL_ADMIN_NAME and a MEDICONNECT_INITIAL_ADMIN_PASSWORD of at least 12 characters.");
        try (PreparedStatement count = c.prepareStatement("SELECT COUNT(*) FROM users WHERE role='ADMIN'")) {
            try (ResultSet rs = count.executeQuery()) { rs.next(); if (rs.getLong(1) > 0) return; }
        }
        User firstAdmin=addUser(name, email, password.toCharArray(), Role.ADMIN);
        try(PreparedStatement protect=c.prepareStatement("UPDATE users SET protected_admin=TRUE WHERE id=?")){protect.setLong(1,firstAdmin.id());protect.executeUpdate();}
    }
    private static RuntimeException db(SQLException ex) { return new IllegalStateException("Database operation failed: " + ex.getMessage(), ex); }
    private static User user(ResultSet rs) throws SQLException { return new User(rs.getLong("id"), rs.getString("name"), rs.getString("email"), rs.getString("password_hash"), Role.valueOf(rs.getString("role")), rs.getBoolean("active")); }
    private static void validateUser(String name, String email, char[] password, Role role) {
        if (name == null || name.isBlank() || name.length() > 120 || email == null || !email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$") || email.length() > 190 || password == null || password.length < 8 || role == null)
            throw new IllegalArgumentException("Enter a name, valid email, and password of at least 8 characters.");
    }
    @Override public User authenticate(String email, char[] password) {
        try (Connection c = Database.connect(); PreparedStatement p = c.prepareStatement("SELECT " + USER_COLUMNS + " FROM users WHERE LOWER(email)=LOWER(?) AND active=TRUE")) {
            p.setString(1,email); try (ResultSet rs=p.executeQuery()) { if (!rs.next()) return null; User u=user(rs); return PasswordUtil.verify(password,u.passwordHash()) ? u : null; }
        } catch(SQLException ex) { throw db(ex); }
    }
    @Override public User addUser(String name,String email,char[] password,Role role) {
        validateUser(name,email,password,role);
        try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("INSERT INTO users(name,email,password_hash,role,active) VALUES(?,?,?,?,TRUE)",Statement.RETURN_GENERATED_KEYS)) {
            p.setString(1,name.trim());p.setString(2,email.trim());p.setString(3,PasswordUtil.hash(password));p.setString(4,role.name());p.executeUpdate();
            try(ResultSet k=p.getGeneratedKeys()){if(!k.next())throw new SQLException("No user ID was returned.");long id=k.getLong(1); if(role==Role.PROFESSIONAL)try(PreparedStatement profile=c.prepareStatement("INSERT INTO professional_profiles(user_id) VALUES(?)")){profile.setLong(1,id);profile.executeUpdate();} return new User(id,name.trim(),email.trim(),"",role,true);}
        } catch(SQLException ex) { if("23000".equals(ex.getSQLState()))throw new IllegalArgumentException("That email is already registered."); throw db(ex); }
    }
    @Override public List<User> users() {
        try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("SELECT "+USER_COLUMNS+" FROM users ORDER BY id");ResultSet rs=p.executeQuery()){List<User> out=new ArrayList<>();while(rs.next())out.add(user(rs));return List.copyOf(out);}catch(SQLException ex){throw db(ex);}
    }
    @Override public List<User> professionals() { return users().stream().filter(u->u.role()==Role.PROFESSIONAL&&u.active()).toList(); }
    @Override public List<Appointment> appointmentsFor(User actor) {
        String filter=actor.role()==Role.ADMIN?"1=1":actor.role()==Role.PATIENT?"a.patient_id=?":"a.professional_id=?";
        try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("SELECT a.*,COALESCE(c.notes,'') notes,COALESCE(c.advice,'') advice FROM appointments a LEFT JOIN consultations c ON c.appointment_id=a.id WHERE "+filter+" ORDER BY a.starts_at DESC")){
            if(actor.role()!=Role.ADMIN)p.setLong(1,actor.id());try(ResultSet rs=p.executeQuery()){List<Appointment> out=new ArrayList<>();while(rs.next())out.add(new Appointment(rs.getLong("id"),rs.getLong("patient_id"),rs.getLong("professional_id"),rs.getTimestamp("starts_at").toLocalDateTime(),rs.getString("consultation_type"),Appointment.Status.valueOf(rs.getString("status")),rs.getString("notes"),rs.getString("advice")));return List.copyOf(out);}
        }catch(SQLException ex){throw db(ex);}
    }
    @Override public Appointment book(User patient,User professional,LocalDateTime at,String type) {
        if(patient.role()!=Role.PATIENT||professional.role()!=Role.PROFESSIONAL)throw new SecurityException("Only patients can book with an active healthcare professional.");
        if(at==null||!at.isAfter(LocalDateTime.now())||type==null||!Set.of("In-person","Video","Follow-up").contains(type))throw new IllegalArgumentException("Choose a valid consultation type and future appointment time.");
        try(Connection c=Database.connect()) { c.setAutoCommit(false); try {
            lockUser(c,professional.id(),Role.PROFESSIONAL);lockUser(c,patient.id(),Role.PATIENT);
            int duration=settingInt(c,"appointment_duration_minutes",30); LocalDateTime end=at.plusMinutes(duration); checkAvailability(c,professional.id(),at,end);
            if(overlap(c,"professional_id",professional.id(),at,end)||overlap(c,"patient_id",patient.id(),at,end))throw new IllegalArgumentException("This time conflicts with an existing appointment.");
            try(PreparedStatement p=c.prepareStatement("INSERT INTO appointments(patient_id,professional_id,starts_at,duration_minutes,consultation_type,status) VALUES(?,?,?,?,?,'SCHEDULED')",Statement.RETURN_GENERATED_KEYS)){
                p.setLong(1,patient.id());p.setLong(2,professional.id());p.setTimestamp(3,Timestamp.valueOf(at));p.setInt(4,duration);p.setString(5,type);p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){if(!k.next())throw new SQLException("No appointment ID was returned.");c.commit();return new Appointment(k.getLong(1),patient.id(),professional.id(),at,type,Appointment.Status.SCHEDULED,"","");}
            }
        } catch(RuntimeException|SQLException ex){c.rollback();if(ex instanceof RuntimeException re)throw re;throw db((SQLException)ex);} finally{c.setAutoCommit(true);} }catch(SQLException ex){throw db(ex);}
    }
    private static void lockUser(Connection c,long id,Role role)throws SQLException {try(PreparedStatement p=c.prepareStatement("SELECT id FROM users WHERE id=? AND role=? AND active=TRUE FOR UPDATE")){p.setLong(1,id);p.setString(2,role.name());try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("Account is unavailable.");}}}
    private static void checkAvailability(Connection c,long professional,LocalDateTime start,LocalDateTime end)throws SQLException{int weekday=start.getDayOfWeek().getValue();try(PreparedStatement count=c.prepareStatement("SELECT COUNT(*) FROM professional_availability WHERE professional_id=? AND weekday=?")){count.setLong(1,professional);count.setInt(2,weekday);try(ResultSet r=count.executeQuery()){r.next();if(r.getInt(1)==0)return;}}try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM professional_availability WHERE professional_id=? AND weekday=? AND available=TRUE AND start_time<=? AND end_time>=? LIMIT 1")){p.setLong(1,professional);p.setInt(2,weekday);p.setTime(3,Time.valueOf(start.toLocalTime()));p.setTime(4,Time.valueOf(end.toLocalTime()));try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("The professional is unavailable at that time.");}}}
    private static boolean overlap(Connection c,String column,long id,LocalDateTime start,LocalDateTime end)throws SQLException {
        if(!Set.of("professional_id","patient_id").contains(column))throw new IllegalArgumentException("Invalid appointment party.");
        String sql="SELECT id FROM appointments WHERE "+column+"=? AND status<>'CANCELLED' AND starts_at<? AND DATE_ADD(starts_at, INTERVAL duration_minutes MINUTE)>? LIMIT 1";
        try(PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,id);p.setTimestamp(2,Timestamp.valueOf(end));p.setTimestamp(3,Timestamp.valueOf(start));try(ResultSet r=p.executeQuery()){return r.next();}}
    }
    private static boolean overlapExcept(Connection c,String column,long id,LocalDateTime start,LocalDateTime end,long except)throws SQLException{if(!Set.of("professional_id","patient_id").contains(column))throw new IllegalArgumentException("Invalid appointment party.");String sql="SELECT id FROM appointments WHERE "+column+"=? AND id<>? AND status<>'CANCELLED' AND starts_at<? AND DATE_ADD(starts_at, INTERVAL duration_minutes MINUTE)>? LIMIT 1";try(PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,id);p.setLong(2,except);p.setTimestamp(3,Timestamp.valueOf(end));p.setTimestamp(4,Timestamp.valueOf(start));try(ResultSet r=p.executeQuery()){return r.next();}}}
    @Override public void cancel(User actor,long id) {
        try(Connection c=Database.connect()){
            LocalDateTime earliest=LocalDateTime.now().plusHours(settingInt(c,"cancellation_notice_hours",0));
            try(PreparedStatement p=c.prepareStatement("UPDATE appointments SET status='CANCELLED' WHERE id=? AND status IN ('SCHEDULED','CONFIRMED') AND starts_at>? AND (?='ADMIN' OR (?='PATIENT' AND patient_id=?) OR (?='PROFESSIONAL' AND professional_id=?))")){
                p.setLong(1,id);p.setTimestamp(2,Timestamp.valueOf(earliest));p.setString(3,actor.role().name());p.setString(4,actor.role().name());p.setLong(5,actor.id());p.setString(6,actor.role().name());p.setLong(7,actor.id());if(p.executeUpdate()==0)throw new IllegalArgumentException("Appointment is not found or falls outside the cancellation window.");
            }
        }catch(SQLException ex){throw db(ex);}
    }
    @Override public void saveConsultation(User actor,long id,String notes,String advice) {
        if(actor.role()!=Role.ADMIN&&actor.role()!=Role.PROFESSIONAL)throw new SecurityException("Only a professional or admin may save consultation notes.");
        if(notes==null||notes.isBlank()||advice==null||advice.isBlank())throw new IllegalArgumentException("Enter consultation notes and advice.");
        try(Connection c=Database.connect()){c.setAutoCommit(false);try(PreparedStatement check=c.prepareStatement("SELECT professional_id,status FROM appointments WHERE id=? FOR UPDATE")){check.setLong(1,id);try(ResultSet r=check.executeQuery()){if(!r.next())throw new IllegalArgumentException("Appointment not found.");if(actor.role()==Role.PROFESSIONAL&&r.getLong("professional_id")!=actor.id())throw new SecurityException("Only the assigned professional may save this consultation.");if("CANCELLED".equals(r.getString("status")))throw new IllegalArgumentException("Cancelled appointments cannot be completed.");}}
            try(PreparedStatement p=c.prepareStatement("INSERT INTO consultations(appointment_id,notes,advice) VALUES(?,?,?) ON DUPLICATE KEY UPDATE notes=VALUES(notes),advice=VALUES(advice),saved_at=CURRENT_TIMESTAMP")){p.setLong(1,id);p.setString(2,notes.trim());p.setString(3,advice.trim());p.executeUpdate();}
            try(PreparedStatement p=c.prepareStatement("UPDATE appointments SET status='COMPLETED' WHERE id=?")){p.setLong(1,id);p.executeUpdate();}c.commit();
        }catch(SQLException ex){throw db(ex);} }
    @Override public HealthRecord recordFor(User actor,long patientId) {
        try(Connection c=Database.connect()){if(actor.role()!=Role.ADMIN&&!(actor.role()==Role.PATIENT&&actor.id()==patientId)&&!(actor.role()==Role.PROFESSIONAL&&hasAssignedAppointment(c,actor.id(),patientId)))throw new SecurityException("You are not authorized to view this health record.");
            try(PreparedStatement p=c.prepareStatement("SELECT * FROM health_records WHERE patient_id=?")){p.setLong(1,patientId);try(ResultSet r=p.executeQuery()){if(!r.next())return new HealthRecord(patientId,"","","","","","");return new HealthRecord(patientId,n(r.getString("blood_group")),n(r.getString("allergies")),n(r.getString("conditions_text")),n(r.getString("medications")),n(r.getString("medical_history")),n(r.getString("emergency_contact")));}}
        }catch(SQLException ex){throw db(ex);}
    }
    private static String n(String s){return s==null?"":s;}
    private static boolean hasAssignedAppointment(Connection c,long professional,long patient)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM appointments WHERE professional_id=? AND patient_id=? LIMIT 1")){p.setLong(1,professional);p.setLong(2,patient);try(ResultSet r=p.executeQuery()){return r.next();}}}
    @Override public void saveRecord(User actor,HealthRecord r){if(actor.role()!=Role.PATIENT||actor.id()!=r.patientId())throw new SecurityException("Patients may only update their own health record.");String sql="INSERT INTO health_records(patient_id,blood_group,allergies,conditions_text,medications,medical_history,emergency_contact) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE blood_group=VALUES(blood_group),allergies=VALUES(allergies),conditions_text=VALUES(conditions_text),medications=VALUES(medications),medical_history=VALUES(medical_history),emergency_contact=VALUES(emergency_contact)";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,r.patientId());p.setString(2,r.bloodGroup());p.setString(3,r.allergies());p.setString(4,r.conditions());p.setString(5,r.medications());p.setString(6,r.history());p.setString(7,r.emergencyContact());p.executeUpdate();}catch(SQLException ex){throw db(ex);}}
    @Override public void setCurrency(String currency){if(!Set.of("INR","USD","EUR","GBP").contains(currency))throw new IllegalArgumentException("Unsupported currency.");try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("INSERT INTO app_settings(setting_key,setting_value) VALUES('default_currency',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")){p.setString(1,currency);p.executeUpdate();}catch(SQLException ex){throw db(ex);}}
    @Override public String currency(){try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("SELECT setting_value FROM app_settings WHERE setting_key='default_currency'" );ResultSet r=p.executeQuery()){return r.next()?r.getString(1):"INR";}catch(SQLException ex){throw db(ex);}}
    private static int settingInt(Connection c,String key,int fallback)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT setting_value FROM app_settings WHERE setting_key=?")){p.setString(1,key);try(ResultSet r=p.executeQuery()){return r.next()?Integer.parseInt(r.getString(1)):fallback;}}}
    @Override public Map<String,Long> analytics(){Map<String,Long> out=new LinkedHashMap<>();try(Connection c=Database.connect();Statement s=c.createStatement()){
        out.put("Users",count(s,"SELECT COUNT(*) FROM users WHERE active=TRUE"));out.put("Patients",count(s,"SELECT COUNT(*) FROM users WHERE role='PATIENT' AND active=TRUE"));out.put("Professionals",count(s,"SELECT COUNT(*) FROM users WHERE role='PROFESSIONAL' AND active=TRUE"));out.put("Appointments",count(s,"SELECT COUNT(*) FROM appointments"));out.put("Upcoming",count(s,"SELECT COUNT(*) FROM appointments WHERE starts_at>NOW() AND status IN ('SCHEDULED','CONFIRMED')"));out.put("Completed",count(s,"SELECT COUNT(*) FROM appointments WHERE status='COMPLETED'"));out.put("Cancelled",count(s,"SELECT COUNT(*) FROM appointments WHERE status='CANCELLED'"));return Map.copyOf(out);
    }catch(SQLException ex){throw db(ex);}}
    private static long count(Statement s,String sql)throws SQLException{try(ResultSet r=s.executeQuery(sql)){r.next();return r.getLong(1);}}
    @Override public List<Availability> availabilityFor(User professional){if(professional.role()!=Role.PROFESSIONAL&&professional.role()!=Role.ADMIN)throw new SecurityException("Only professionals can manage availability.");String sql="SELECT id,professional_id,weekday,start_time,end_time,available FROM professional_availability WHERE "+(professional.role()==Role.ADMIN?"1=1":"professional_id=?")+" ORDER BY weekday";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(sql)){if(professional.role()!=Role.ADMIN)p.setLong(1,professional.id());try(ResultSet r=p.executeQuery()){List<Availability> list=new ArrayList<>();while(r.next())list.add(new Availability(r.getLong("id"),r.getLong("professional_id"),DayOfWeek.of(r.getInt("weekday")),r.getTime("start_time").toLocalTime(),r.getTime("end_time").toLocalTime(),r.getBoolean("available")));return List.copyOf(list);}}catch(SQLException ex){throw db(ex);}}
    @Override public void saveAvailability(User actor,DayOfWeek day,LocalTime start,LocalTime end,boolean available){if(actor.role()!=Role.PROFESSIONAL)throw new SecurityException("Only professionals can manage their schedule.");if(day==null||start==null||end==null||!start.isBefore(end))throw new IllegalArgumentException("Select a working day and valid start/end times.");try(Connection c=Database.connect()){c.setAutoCommit(false);try(PreparedStatement d=c.prepareStatement("DELETE FROM professional_availability WHERE professional_id=? AND weekday=?")){d.setLong(1,actor.id());d.setInt(2,day.getValue());d.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO professional_availability(professional_id,weekday,start_time,end_time,available) VALUES(?,?,?,?,?)")){p.setLong(1,actor.id());p.setInt(2,day.getValue());p.setTime(3,Time.valueOf(start));p.setTime(4,Time.valueOf(end));p.setBoolean(5,available);p.executeUpdate();}c.commit();}catch(SQLException ex){throw db(ex);}}
    @Override public List<Message> messagesFor(User actor){try(Connection c=Database.connect()){try(PreparedStatement mark=c.prepareStatement("UPDATE messages SET read_at=NOW() WHERE recipient_id=? AND read_at IS NULL")){mark.setLong(1,actor.id());mark.executeUpdate();}try(PreparedStatement p=c.prepareStatement("SELECT id,sender_id,recipient_id,body,sent_at,read_at FROM messages WHERE sender_id=? OR recipient_id=? ORDER BY sent_at")){p.setLong(1,actor.id());p.setLong(2,actor.id());try(ResultSet r=p.executeQuery()){List<Message> out=new ArrayList<>();while(r.next())out.add(new Message(r.getLong("id"),r.getLong("sender_id"),r.getLong("recipient_id"),r.getString("body"),r.getTimestamp("sent_at").toLocalDateTime(),r.getTimestamp("read_at")!=null));return List.copyOf(out);}}}catch(SQLException ex){throw db(ex);}}
    @Override public void sendMessage(User actor,long recipientId,String body){if(body==null||body.isBlank()||body.length()>4000)throw new IllegalArgumentException("Enter a message (up to 4,000 characters).");try(Connection c=Database.connect()){User recipient;try(PreparedStatement p=c.prepareStatement("SELECT "+USER_COLUMNS+" FROM users WHERE id=? AND active=TRUE")){p.setLong(1,recipientId);try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("Recipient account not found.");recipient=user(r);}}if(actor.role()==recipient.role()||!hasAssignedAppointment(c,actor.role()==Role.PATIENT?recipientId:actor.id(),actor.role()==Role.PATIENT?actor.id():recipientId))throw new SecurityException("Messages are limited to patients and professionals connected by an appointment.");try(PreparedStatement p=c.prepareStatement("INSERT INTO messages(sender_id,recipient_id,body) VALUES(?,?,?)")){p.setLong(1,actor.id());p.setLong(2,recipientId);p.setString(3,body.trim());p.executeUpdate();}}catch(SQLException ex){throw db(ex);}}
    @Override public void setUserActive(User actor,long id,boolean active){if(actor.role()!=Role.ADMIN)throw new SecurityException("Administrator access is required.");if(id==actor.id()&&!active)throw new IllegalArgumentException("You cannot deactivate your own account.");try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("UPDATE users SET active=? WHERE id=? AND NOT (protected_admin=TRUE AND ?=FALSE)")){p.setBoolean(1,active);p.setLong(2,id);p.setBoolean(3,active);if(p.executeUpdate()==0)throw new IllegalArgumentException("User not found, or the initial administrator is protected.");}catch(SQLException ex){throw db(ex);}}
    @Override public void setAppointmentStatus(User actor,long id,Appointment.Status status){if(actor.role()!=Role.ADMIN)throw new SecurityException("Administrator access is required.");if(status==null)throw new IllegalArgumentException("Choose an appointment status.");try(Connection c=Database.connect()){c.setAutoCommit(false);try(PreparedStatement q=c.prepareStatement("SELECT status,(SELECT COUNT(*) FROM consultations c WHERE c.appointment_id=appointments.id) consultation_count FROM appointments WHERE id=? FOR UPDATE")){q.setLong(1,id);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("Appointment not found.");if("COMPLETED".equals(r.getString("status"))&&status!=Appointment.Status.COMPLETED)throw new IllegalArgumentException("Completed consultations retain their history and cannot be reopened.");if(status==Appointment.Status.COMPLETED&&r.getInt("consultation_count")==0)throw new IllegalArgumentException("A consultation record is required before completion.");}}try(PreparedStatement p=c.prepareStatement("UPDATE appointments SET status=? WHERE id=?")){p.setString(1,status.name());p.setLong(2,id);p.executeUpdate();}c.commit();}catch(SQLException ex){throw db(ex);}}
    @Override public Appointment reschedule(User actor,long id,LocalDateTime at){if(at==null||!at.isAfter(LocalDateTime.now()))throw new IllegalArgumentException("Choose a future date and time.");try(Connection c=Database.connect()){c.setAutoCommit(false);try(PreparedStatement q=c.prepareStatement("SELECT * FROM appointments WHERE id=? FOR UPDATE")){q.setLong(1,id);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("Appointment not found.");long patient=r.getLong("patient_id"),professional=r.getLong("professional_id");String state=r.getString("status");LocalDateTime old=r.getTimestamp("starts_at").toLocalDateTime();if(actor.role()!=Role.ADMIN&&actor.id()!=patient&&actor.id()!=professional)throw new SecurityException("You cannot manage this appointment.");if(!Set.of("SCHEDULED","CONFIRMED").contains(state)||!old.isAfter(LocalDateTime.now()))throw new IllegalArgumentException("This appointment can no longer be rescheduled.");lockUser(c,professional,Role.PROFESSIONAL);lockUser(c,patient,Role.PATIENT);int duration=r.getInt("duration_minutes");LocalDateTime end=at.plusMinutes(duration);checkAvailability(c,professional,at,end);if(overlapExcept(c,"professional_id",professional,at,end,id)||overlapExcept(c,"patient_id",patient,at,end,id))throw new IllegalArgumentException("This time conflicts with another appointment.");String type=r.getString("consultation_type");try(PreparedStatement u=c.prepareStatement("UPDATE appointments SET starts_at=? WHERE id=?")){u.setTimestamp(1,Timestamp.valueOf(at));u.setLong(2,id);u.executeUpdate();}c.commit();return new Appointment(id,patient,professional,at,type,Appointment.Status.valueOf(state),"","");}}catch(RuntimeException|SQLException ex){c.rollback();if(ex instanceof RuntimeException re)throw re;throw db((SQLException)ex);}finally{c.setAutoCommit(true);}}catch(SQLException ex){throw db(ex);}}
    @Override public User updateProfile(User actor,String name,String email){if(name==null||name.isBlank()||name.length()>120||email==null||email.length()>190||!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))throw new IllegalArgumentException("Enter a valid name and email.");try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("UPDATE users SET name=?,email=? WHERE id=? AND active=TRUE")){p.setString(1,name.trim());p.setString(2,email.trim());p.setLong(3,actor.id());if(p.executeUpdate()==0)throw new IllegalArgumentException("Account is unavailable.");try(PreparedStatement q=c.prepareStatement("SELECT "+USER_COLUMNS+" FROM users WHERE id=?")){q.setLong(1,actor.id());try(ResultSet r=q.executeQuery()){r.next();return user(r);}}}catch(SQLException ex){if("23000".equals(ex.getSQLState()))throw new IllegalArgumentException("That email is already registered.");throw db(ex);}}
    @Override public void changePassword(User actor,char[] current,char[] next){if(next==null||next.length<8)throw new IllegalArgumentException("New password must be at least 8 characters.");try(Connection c=Database.connect();PreparedStatement q=c.prepareStatement("SELECT password_hash FROM users WHERE id=? AND active=TRUE")){q.setLong(1,actor.id());try(ResultSet r=q.executeQuery()){if(!r.next()||!PasswordUtil.verify(current,r.getString(1)))throw new IllegalArgumentException("Current password is incorrect.");}try(PreparedStatement p=c.prepareStatement("UPDATE users SET password_hash=? WHERE id=?")){p.setString(1,PasswordUtil.hash(next));p.setLong(2,actor.id());p.executeUpdate();}}catch(SQLException ex){throw db(ex);}}
    @Override public User adminUpdateUser(User actor,long id,String name,String email,Role role){if(actor.role()!=Role.ADMIN)throw new SecurityException("Administrator access is required.");if(name==null||name.isBlank()||name.length()>120||email==null||email.length()>190||!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")||role==null)throw new IllegalArgumentException("Enter a name, valid email, and role.");try(Connection c=Database.connect()){c.setAutoCommit(false);Role oldRole;try(PreparedStatement q=c.prepareStatement("SELECT role,protected_admin,(SELECT COUNT(*) FROM appointments WHERE patient_id=users.id OR professional_id=users.id) appointment_count FROM users WHERE id=? FOR UPDATE")){q.setLong(1,id);try(ResultSet r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("User not found.");oldRole=Role.valueOf(r.getString("role"));if(r.getBoolean("protected_admin")&&role!=Role.ADMIN)throw new IllegalArgumentException("The initial administrator role is protected.");if(oldRole!=role&&r.getLong("appointment_count")>0)throw new IllegalArgumentException("Account roles cannot change while appointments are attached.");}}try(PreparedStatement p=c.prepareStatement("UPDATE users SET name=?,email=?,role=? WHERE id=?")){p.setString(1,name.trim());p.setString(2,email.trim());p.setString(3,role.name());p.setLong(4,id);p.executeUpdate();}if(role==Role.PROFESSIONAL){try(PreparedStatement p=c.prepareStatement("INSERT IGNORE INTO professional_profiles(user_id) VALUES(?)")){p.setLong(1,id);p.executeUpdate();}}else if(oldRole==Role.PROFESSIONAL){try(PreparedStatement p=c.prepareStatement("DELETE FROM professional_profiles WHERE user_id=?")){p.setLong(1,id);p.executeUpdate();}}c.commit();try(PreparedStatement q=c.prepareStatement("SELECT "+USER_COLUMNS+" FROM users WHERE id=?")){q.setLong(1,id);try(ResultSet r=q.executeQuery()){r.next();return user(r);}}}catch(SQLException ex){if("23000".equals(ex.getSQLState()))throw new IllegalArgumentException("That email is already registered.");throw db(ex);}}
    @Override public Map<String,String> settings(){try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("SELECT setting_key,setting_value FROM app_settings");ResultSet r=p.executeQuery()){Map<String,String> values=new LinkedHashMap<>();while(r.next())values.put(r.getString(1),r.getString(2));values.putIfAbsent("application_name","MediConnect");values.putIfAbsent("appointment_duration_minutes","30");values.putIfAbsent("cancellation_notice_hours","0");values.putIfAbsent("default_currency","INR");return Map.copyOf(values);}catch(SQLException ex){throw db(ex);}}
    @Override public void updateSetting(User actor,String key,String value){if(actor.role()!=Role.ADMIN)throw new SecurityException("Administrator access is required.");if(value==null)throw new IllegalArgumentException("A setting value is required.");switch(key){case "application_name"->{if(value.isBlank()||value.length()>80)throw new IllegalArgumentException("Application name must be 1–80 characters.");}case "appointment_duration_minutes"->{int n=parseSetting(value,"Appointment duration");if(n<15||n>120||n%15!=0)throw new IllegalArgumentException("Choose a duration from 15 to 120 minutes in 15-minute increments.");}case "cancellation_notice_hours"->{int n=parseSetting(value,"Cancellation notice");if(n<0||n>168)throw new IllegalArgumentException("Cancellation notice must be from 0 to 168 hours.");}case "default_currency"->{setCurrency(value);return;}default->throw new IllegalArgumentException("This setting cannot be changed.");}try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("INSERT INTO app_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")){p.setString(1,key);p.setString(2,value.trim());p.executeUpdate();}catch(SQLException ex){throw db(ex);}}
    private static int parseSetting(String value,String label){try{return Integer.parseInt(value);}catch(NumberFormatException ex){throw new IllegalArgumentException(label+" must be a number.");}}
}
