package com.mediconnect.service;

import com.mediconnect.model.*;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

class PlatformServiceTest {
    @Test void demoAccountsAuthenticateAndInvalidPasswordFails() { PlatformService s=new PlatformService(); assertEquals(Role.PATIENT,s.authenticate("patient@demo.local","Patient123!".toCharArray()).role()); assertNull(s.authenticate("patient@demo.local","wrongpass".toCharArray())); }
    @Test void creationValidatesAndRejectsDuplicateEmail() { PlatformService s=new PlatformService(); assertThrows(IllegalArgumentException.class,()->s.addUser("X","bad","password1".toCharArray(),Role.PATIENT)); assertThrows(IllegalArgumentException.class,()->s.addUser("Other","PATIENT@DEMO.LOCAL","password1".toCharArray(),Role.PATIENT)); }
    @Test void bookingRejectsPastAndDuplicateSlotsAndRestrictsCancellation() { PlatformService s=new PlatformService(); User p=s.authenticate("patient@demo.local","Patient123!".toCharArray()), d=s.authenticate("doctor@demo.local","Doctor123!".toCharArray()); assertThrows(IllegalArgumentException.class,()->s.book(p,d,LocalDateTime.now().minusDays(1),"Video")); LocalDateTime slot=LocalDateTime.now().plusDays(2); Appointment a=s.book(p,d,slot,"Video"); assertThrows(IllegalArgumentException.class,()->s.book(p,d,slot,"Video")); User other=s.addUser("Other","other@demo.local","OtherPass123".toCharArray(),Role.PATIENT); assertThrows(SecurityException.class,()->s.cancel(other,a.id())); s.cancel(p,a.id()); assertEquals(Appointment.Status.CANCELLED,s.appointmentsFor(p).get(0).status()); }
    @Test void recordAccessAndCurrencyAreValidated() { PlatformService s=new PlatformService(); User p=s.authenticate("patient@demo.local","Patient123!".toCharArray()), other=s.addUser("Other","other@demo.local","OtherPass123".toCharArray(),Role.PATIENT); assertThrows(SecurityException.class,()->s.recordFor(other,p.id())); s.saveRecord(p,new HealthRecord(p.id(),"O+","","","","","")); assertEquals("O+",s.recordFor(p,p.id()).bloodGroup()); assertThrows(IllegalArgumentException.class,()->s.setCurrency("CAD")); }
    @Test void onlyAssignedProfessionalCanCompleteConsultation() { PlatformService s=new PlatformService(); User p=s.authenticate("patient@demo.local","Patient123!".toCharArray()), d=s.authenticate("doctor@demo.local","Doctor123!".toCharArray()), other=s.addUser("Dr Other","otherdoc@demo.local","OtherPass123".toCharArray(),Role.PROFESSIONAL); Appointment a=s.book(p,d,LocalDateTime.now().plusDays(4),"Video"); assertThrows(SecurityException.class,()->s.saveConsultation(other,a.id(),"n","a")); s.saveConsultation(d,a.id(),"notes","advice"); assertEquals(Appointment.Status.COMPLETED,s.appointmentsFor(d).get(0).status()); }
    @Test void availabilityMessagingAndAdminRestrictionsWork() { PlatformService s=new PlatformService(); User p=s.authenticate("patient@demo.local","Patient123!".toCharArray()), d=s.authenticate("doctor@demo.local","Doctor123!".toCharArray()), admin=s.authenticate("admin@demo.local","Admin123!".toCharArray()); LocalDateTime slot=LocalDateTime.now().plusDays(5).withHour(10).withMinute(0).withSecond(0).withNano(0); s.saveAvailability(d,slot.getDayOfWeek(),java.time.LocalTime.of(9,0),java.time.LocalTime.of(17,0),true); Appointment a=s.book(p,d,slot,"Video"); assertEquals(1,s.availabilityFor(d).size()); s.sendMessage(p,d.id(),"Hello, I have a question."); assertEquals(1,s.messagesFor(d).size()); assertTrue(s.messagesFor(d).get(0).read()); s.setAppointmentStatus(admin,a.id(),Appointment.Status.CONFIRMED); assertEquals(Appointment.Status.CONFIRMED,s.appointmentsFor(p).get(0).status()); assertThrows(IllegalArgumentException.class,()->s.setUserActive(admin,admin.id(),false)); assertThrows(SecurityException.class,()->s.setUserActive(p,d.id(),false)); }
    @Test void profilePasswordSettingsAndRescheduleAreValidated() { PlatformService s=new PlatformService(); User p=s.authenticate("patient@demo.local","Patient123!".toCharArray()), d=s.authenticate("doctor@demo.local","Doctor123!".toCharArray()), admin=s.authenticate("admin@demo.local","Admin123!".toCharArray()); User changed=s.updateProfile(p,"Sam New","sam.new@demo.local"); assertEquals("sam.new@demo.local",changed.email()); s.changePassword(changed,"Patient123!".toCharArray(),"NewPatient123!".toCharArray()); assertNotNull(s.authenticate("sam.new@demo.local","NewPatient123!".toCharArray())); assertThrows(IllegalArgumentException.class,()->s.changePassword(changed,"wrong".toCharArray(),"somethingnew".toCharArray())); s.updateSetting(admin,"appointment_duration_minutes","45"); assertEquals("45",s.settings().get("appointment_duration_minutes")); assertThrows(IllegalArgumentException.class,()->s.updateSetting(admin,"appointment_duration_minutes","20")); LocalDateTime first=LocalDateTime.now().plusDays(6).withHour(10).withMinute(0).withSecond(0).withNano(0); Appointment a=s.book(changed,d,first,"Video"); LocalDateTime next=first.plusDays(1); assertEquals(next,s.reschedule(changed,a.id(),next).startsAt()); User other=s.addUser("Other","other@demo.local","OtherPass123".toCharArray(),Role.PATIENT); assertThrows(SecurityException.class,()->s.reschedule(other,a.id(),next.plusDays(1))); }
    @Test void adminCanEditUnassignedAccountsButCannotDemoteInitialAdmin(){PlatformService s=new PlatformService();User admin=s.authenticate("admin@demo.local","Admin123!".toCharArray());User created=s.addUser("New User","new@demo.local","NewUserPass1".toCharArray(),Role.PATIENT);User edited=s.adminUpdateUser(admin,created.id(),"Dr New","doctor.new@demo.local",Role.PROFESSIONAL);assertEquals(Role.PROFESSIONAL,edited.role());assertEquals("doctor.new@demo.local",edited.email());assertThrows(IllegalArgumentException.class,()->s.adminUpdateUser(admin,admin.id(),admin.name(),admin.email(),Role.PATIENT));}
}
